import React from 'react';

const TermsConditions: React.FC = () => {
  return (
    <div className="min-h-screen bg-[#0b0e14] text-[#c9d1d9] py-12 px-6 overflow-y-auto">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-4xl font-black text-white mb-4">Terms & Conditions</h1>
        <p className="text-sm text-slate-500 mb-8">Effective Date: January 1, 2025 | Last Updated: January 1, 2025</p>

        <section className="space-y-8">
          <div>
            <h2 className="text-2xl font-bold text-blue-400 mb-3">1. Acceptance of Terms</h2>
            <p className="text-slate-300 leading-relaxed">
              By accessing and using Terra.ai ("Platform", "Service"), you accept and agree to be bound by these Terms and Conditions. If you do not agree to these terms, please do not use our platform.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-bold text-blue-400 mb-3">2. Service Description</h2>
            <p className="text-slate-300 leading-relaxed mb-3">
              Terra.ai is an independent AI-powered platform that generates infrastructure-as-code (Terraform) for cloud deployments. The platform provides:
            </p>
            <ul className="list-disc list-inside text-slate-300 space-y-2">
              <li>AI-generated Terraform code for AWS infrastructure</li>
              <li>Project management and code storage</li>
              <li>Code export and download capabilities</li>
              <li>DevOps project templates (Premium feature)</li>
            </ul>
          </div>

          <div>
            <h2 className="text-2xl font-bold text-blue-400 mb-3">3. User Accounts</h2>
            <h3 className="text-lg font-semibold text-white mt-4 mb-2">3.1 Registration</h3>
            <p className="text-slate-300 leading-relaxed">
              You must create an account to use the platform. You agree to provide accurate, current, and complete information during registration and keep your account information updated.
            </p>
            <h3 className="text-lg font-semibold text-white mt-4 mb-2">3.2 Account Security</h3>
            <p className="text-slate-300 leading-relaxed">
              You are responsible for maintaining the confidentiality of your account credentials and for all activities under your account. Notify us immediately of any unauthorized access.
            </p>
            <h3 className="text-lg font-semibold text-white mt-4 mb-2">3.3 Account Termination</h3>
            <p className="text-slate-300 leading-relaxed">
              We reserve the right to suspend or terminate accounts that violate these terms or engage in fraudulent, abusive, or illegal activities.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-bold text-blue-400 mb-3">4. Subscription Plans</h2>
            <h3 className="text-lg font-semibold text-white mt-4 mb-2">4.1 Free Plan</h3>
            <ul className="list-disc list-inside text-slate-300 space-y-1">
              <li>Limited to 3 projects</li>
              <li>Basic AI code generation</li>
              <li>No access to DevOps templates</li>
            </ul>
            <h3 className="text-lg font-semibold text-white mt-4 mb-2">4.2 Premium Plans</h3>
            <ul className="list-disc list-inside text-slate-300 space-y-1">
              <li>Monthly Plan: ₹499/month - Unlimited projects, DevOps templates, priority support</li>
              <li>Yearly Plan: ₹4999/year - All monthly features + 2 months free</li>
            </ul>
            <h3 className="text-lg font-semibold text-white mt-4 mb-2">4.3 Billing</h3>
            <p className="text-slate-300 leading-relaxed">
              Subscriptions are billed in advance on a monthly or yearly basis. Payments are processed securely through third-party payment processors. All prices are in Indian Rupees (INR).
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-bold text-blue-400 mb-3">5. AI-Generated Content</h2>
            <h3 className="text-lg font-semibold text-white mt-4 mb-2">5.1 No Warranty</h3>
            <p className="text-slate-300 leading-relaxed">
              All infrastructure code generated by our AI is provided "AS-IS" without any warranties, express or implied. We do not guarantee that the generated code is error-free, secure, or suitable for production use.
            </p>
            <h3 className="text-lg font-semibold text-white mt-4 mb-2">5.2 User Responsibility</h3>
            <p className="text-slate-300 leading-relaxed mb-3">
              You are solely responsible for:
            </p>
            <ul className="list-disc list-inside text-slate-300 space-y-2">
              <li>Reviewing and validating all AI-generated code before deployment</li>
              <li>Testing infrastructure in non-production environments</li>
              <li>Ensuring compliance with security and regulatory requirements</li>
              <li>Any costs, damages, or issues arising from deploying generated code</li>
            </ul>
            <h3 className="text-lg font-semibold text-white mt-4 mb-2">5.3 Intellectual Property</h3>
            <p className="text-slate-300 leading-relaxed">
              You retain ownership of the code generated through the platform. However, you acknowledge that similar code may be generated for other users based on similar prompts.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-bold text-blue-400 mb-3">6. Acceptable Use Policy</h2>
            <p className="text-slate-300 leading-relaxed mb-3">You agree NOT to:</p>
            <ul className="list-disc list-inside text-slate-300 space-y-2">
              <li>Use the platform for illegal activities or malicious purposes</li>
              <li>Attempt to reverse engineer, hack, or compromise the platform</li>
              <li>Share your account credentials with others</li>
              <li>Generate code intended to harm, exploit, or attack systems</li>
              <li>Violate any applicable laws or regulations</li>
              <li>Resell or redistribute generated code as a service</li>
            </ul>
          </div>

          <div>
            <h2 className="text-2xl font-bold text-blue-400 mb-3">7. Limitation of Liability</h2>
            <p className="text-slate-300 leading-relaxed mb-3">
              To the maximum extent permitted by law:
            </p>
            <ul className="list-disc list-inside text-slate-300 space-y-2">
              <li>We are not liable for any direct, indirect, incidental, or consequential damages arising from your use of the platform</li>
              <li>We are not responsible for infrastructure failures, data loss, or security breaches resulting from deployed code</li>
              <li>Our total liability shall not exceed the amount you paid for the service in the past 12 months</li>
              <li>We are not liable for third-party services, cloud provider costs, or deployment issues</li>
            </ul>
          </div>

          <div>
            <h2 className="text-2xl font-bold text-blue-400 mb-3">8. Independent Platform Notice</h2>
            <p className="text-slate-300 leading-relaxed mb-3">
              Terra.ai is an independent platform. We are NOT affiliated with, endorsed by, or connected to:
            </p>
            <ul className="list-disc list-inside text-slate-300 space-y-1">
              <li>Amazon Web Services (AWS), Amazon, or any AWS service</li>
              <li>Microsoft Azure, Microsoft, or any Azure service</li>
              <li>Google Cloud Platform (GCP), Google, or any GCP service</li>
              <li>HashiCorp, Terraform (the tool), or any HashiCorp product</li>
              <li>OpenAI, Anthropic, or any AI company</li>
            </ul>
            <p className="text-slate-300 leading-relaxed mt-3">
              All trademarks, service marks, and company names are the property of their respective owners. Use of these names is for descriptive purposes only and does not imply endorsement.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-bold text-blue-400 mb-3">9. Service Availability</h2>
            <p className="text-slate-300 leading-relaxed">
              We strive to maintain 99% uptime but do not guarantee uninterrupted service. We may perform maintenance, updates, or experience downtime without prior notice. We are not liable for service interruptions.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-bold text-blue-400 mb-3">10. Modifications to Terms</h2>
            <p className="text-slate-300 leading-relaxed">
              We reserve the right to modify these Terms and Conditions at any time. Changes will be posted on this page with an updated "Last Updated" date. Continued use of the platform after changes constitutes acceptance of the updated terms.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-bold text-blue-400 mb-3">11. Termination</h2>
            <p className="text-slate-300 leading-relaxed">
              You may terminate your account at any time by contacting support. We may terminate or suspend your account immediately for violations of these terms. Upon termination, your access to the platform and stored data will be removed.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-bold text-blue-400 mb-3">12. Governing Law</h2>
            <p className="text-slate-300 leading-relaxed">
              These Terms and Conditions are governed by the laws of India. Any disputes shall be resolved in the courts of India.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-bold text-blue-400 mb-3">13. Contact Information</h2>
            <p className="text-slate-300 leading-relaxed">
              For questions about these Terms and Conditions:
            </p>
            <div className="mt-3 text-slate-300">
              <p><strong>Email:</strong> <a href="mailto:pm.terra.ai@gmail.com" className="text-blue-400 hover:underline">pm.terra.ai@gmail.com</a></p>
              <p><strong>Support:</strong> <a href="mailto:pm.terra.ai@gmail.com" className="text-blue-400 hover:underline">pm.terra.ai@gmail.com</a></p>
            </div>
          </div>
        </section>

        <div className="mt-12 pt-8 border-t border-[#30363d] text-center">
          <p className="text-slate-500 text-sm">
            By using Terra.ai, you acknowledge that you have read, understood, and agree to be bound by these Terms and Conditions.
          </p>
        </div>
      </div>
    </div>
  );
};

export default TermsConditions;
